// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//消息ID
type ID int32

const (
	ID_MSG_BEGIN     ID = 0
	ID_MSG_Connect   ID = 1
	ID_MSG_Heartbeat ID = 2
	ID_MSG_JoinRoom  ID = 10
	ID_MSG_Progress  ID = 20
	ID_MSG_Ready     ID = 30
	ID_MSG_Start     ID = 40
	ID_MSG_Frame     ID = 50
	ID_MSG_Input     ID = 60
	ID_MSG_Result    ID = 70
	ID_MSG_Close     ID = 100
	ID_MSG_END       ID = 255
)

var ID_name = map[int32]string{
	0:   "MSG_BEGIN",
	1:   "MSG_Connect",
	2:   "MSG_Heartbeat",
	10:  "MSG_JoinRoom",
	20:  "MSG_Progress",
	30:  "MSG_Ready",
	40:  "MSG_Start",
	50:  "MSG_Frame",
	60:  "MSG_Input",
	70:  "MSG_Result",
	100: "MSG_Close",
	255: "MSG_END",
}

var ID_value = map[string]int32{
	"MSG_BEGIN":     0,
	"MSG_Connect":   1,
	"MSG_Heartbeat": 2,
	"MSG_JoinRoom":  10,
	"MSG_Progress":  20,
	"MSG_Ready":     30,
	"MSG_Start":     40,
	"MSG_Frame":     50,
	"MSG_Input":     60,
	"MSG_Result":    70,
	"MSG_Close":     100,
	"MSG_END":       255,
}

func (x ID) Enum() *ID {
	p := new(ID)
	*p = x
	return p
}

func (x ID) String() string {
	return proto.EnumName(ID_name, int32(x))
}

func (x *ID) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ID_value, data, "ID")
	if err != nil {
		return err
	}
	*x = ID(value)
	return nil
}

func (ID) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

//错误码
type ERRORCODE int32

const (
	ERRORCODE_ERR_Ok        ERRORCODE = 0
	ERRORCODE_ERR_NoPlayer  ERRORCODE = 1
	ERRORCODE_ERR_NoRoom    ERRORCODE = 2
	ERRORCODE_ERR_RoomState ERRORCODE = 3
	ERRORCODE_ERR_Token     ERRORCODE = 4
)

var ERRORCODE_name = map[int32]string{
	0: "ERR_Ok",
	1: "ERR_NoPlayer",
	2: "ERR_NoRoom",
	3: "ERR_RoomState",
	4: "ERR_Token",
}

var ERRORCODE_value = map[string]int32{
	"ERR_Ok":        0,
	"ERR_NoPlayer":  1,
	"ERR_NoRoom":    2,
	"ERR_RoomState": 3,
	"ERR_Token":     4,
}

func (x ERRORCODE) Enum() *ERRORCODE {
	p := new(ERRORCODE)
	*p = x
	return p
}

func (x ERRORCODE) String() string {
	return proto.EnumName(ERRORCODE_name, int32(x))
}

func (x *ERRORCODE) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ERRORCODE_value, data, "ERRORCODE")
	if err != nil {
		return err
	}
	*x = ERRORCODE(value)
	return nil
}

func (ERRORCODE) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}

//客户端发来的第一个消息
type C2S_ConnectMsg struct {
	PlayerID             *uint64  `protobuf:"varint,1,opt,name=playerID" json:"playerID,omitempty"`
	BattleID             *uint64  `protobuf:"varint,2,opt,name=battleID" json:"battleID,omitempty"`
	Token                *string  `protobuf:"bytes,10,opt,name=token" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2S_ConnectMsg) Reset()         { *m = C2S_ConnectMsg{} }
func (m *C2S_ConnectMsg) String() string { return proto.CompactTextString(m) }
func (*C2S_ConnectMsg) ProtoMessage()    {}
func (*C2S_ConnectMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

func (m *C2S_ConnectMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2S_ConnectMsg.Unmarshal(m, b)
}
func (m *C2S_ConnectMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2S_ConnectMsg.Marshal(b, m, deterministic)
}
func (m *C2S_ConnectMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2S_ConnectMsg.Merge(m, src)
}
func (m *C2S_ConnectMsg) XXX_Size() int {
	return xxx_messageInfo_C2S_ConnectMsg.Size(m)
}
func (m *C2S_ConnectMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_C2S_ConnectMsg.DiscardUnknown(m)
}

var xxx_messageInfo_C2S_ConnectMsg proto.InternalMessageInfo

func (m *C2S_ConnectMsg) GetPlayerID() uint64 {
	if m != nil && m.PlayerID != nil {
		return *m.PlayerID
	}
	return 0
}

func (m *C2S_ConnectMsg) GetBattleID() uint64 {
	if m != nil && m.BattleID != nil {
		return *m.BattleID
	}
	return 0
}

func (m *C2S_ConnectMsg) GetToken() string {
	if m != nil && m.Token != nil {
		return *m.Token
	}
	return ""
}

//服务端返回连接结果
type S2C_ConnectMsg struct {
	ErrorCode            *ERRORCODE `protobuf:"varint,1,opt,name=errorCode,enum=pb.ERRORCODE" json:"errorCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *S2C_ConnectMsg) Reset()         { *m = S2C_ConnectMsg{} }
func (m *S2C_ConnectMsg) String() string { return proto.CompactTextString(m) }
func (*S2C_ConnectMsg) ProtoMessage()    {}
func (*S2C_ConnectMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}

func (m *S2C_ConnectMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2C_ConnectMsg.Unmarshal(m, b)
}
func (m *S2C_ConnectMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2C_ConnectMsg.Marshal(b, m, deterministic)
}
func (m *S2C_ConnectMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2C_ConnectMsg.Merge(m, src)
}
func (m *S2C_ConnectMsg) XXX_Size() int {
	return xxx_messageInfo_S2C_ConnectMsg.Size(m)
}
func (m *S2C_ConnectMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_S2C_ConnectMsg.DiscardUnknown(m)
}

var xxx_messageInfo_S2C_ConnectMsg proto.InternalMessageInfo

func (m *S2C_ConnectMsg) GetErrorCode() ERRORCODE {
	if m != nil && m.ErrorCode != nil {
		return *m.ErrorCode
	}
	return ERRORCODE_ERR_Ok
}

//服务端返回进入房间消息
type S2C_JoinRoomMsg struct {
	Roomseatid           *int32   `protobuf:"varint,1,opt,name=roomseatid" json:"roomseatid,omitempty"`
	Others               []uint64 `protobuf:"varint,2,rep,name=others" json:"others,omitempty"`
	Pros                 []int32  `protobuf:"varint,3,rep,name=pros" json:"pros,omitempty"`
	RandomSeed           *int32   `protobuf:"varint,4,opt,name=randomSeed" json:"randomSeed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *S2C_JoinRoomMsg) Reset()         { *m = S2C_JoinRoomMsg{} }
func (m *S2C_JoinRoomMsg) String() string { return proto.CompactTextString(m) }
func (*S2C_JoinRoomMsg) ProtoMessage()    {}
func (*S2C_JoinRoomMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{2}
}

func (m *S2C_JoinRoomMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2C_JoinRoomMsg.Unmarshal(m, b)
}
func (m *S2C_JoinRoomMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2C_JoinRoomMsg.Marshal(b, m, deterministic)
}
func (m *S2C_JoinRoomMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2C_JoinRoomMsg.Merge(m, src)
}
func (m *S2C_JoinRoomMsg) XXX_Size() int {
	return xxx_messageInfo_S2C_JoinRoomMsg.Size(m)
}
func (m *S2C_JoinRoomMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_S2C_JoinRoomMsg.DiscardUnknown(m)
}

var xxx_messageInfo_S2C_JoinRoomMsg proto.InternalMessageInfo

func (m *S2C_JoinRoomMsg) GetRoomseatid() int32 {
	if m != nil && m.Roomseatid != nil {
		return *m.Roomseatid
	}
	return 0
}

func (m *S2C_JoinRoomMsg) GetOthers() []uint64 {
	if m != nil {
		return m.Others
	}
	return nil
}

func (m *S2C_JoinRoomMsg) GetPros() []int32 {
	if m != nil {
		return m.Pros
	}
	return nil
}

func (m *S2C_JoinRoomMsg) GetRandomSeed() int32 {
	if m != nil && m.RandomSeed != nil {
		return *m.RandomSeed
	}
	return 0
}

//服务端广播开始游戏消息
type S2C_StartMsg struct {
	TimeStamp            *int64   `protobuf:"varint,1,opt,name=timeStamp" json:"timeStamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *S2C_StartMsg) Reset()         { *m = S2C_StartMsg{} }
func (m *S2C_StartMsg) String() string { return proto.CompactTextString(m) }
func (*S2C_StartMsg) ProtoMessage()    {}
func (*S2C_StartMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{3}
}

func (m *S2C_StartMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2C_StartMsg.Unmarshal(m, b)
}
func (m *S2C_StartMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2C_StartMsg.Marshal(b, m, deterministic)
}
func (m *S2C_StartMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2C_StartMsg.Merge(m, src)
}
func (m *S2C_StartMsg) XXX_Size() int {
	return xxx_messageInfo_S2C_StartMsg.Size(m)
}
func (m *S2C_StartMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_S2C_StartMsg.DiscardUnknown(m)
}

var xxx_messageInfo_S2C_StartMsg proto.InternalMessageInfo

func (m *S2C_StartMsg) GetTimeStamp() int64 {
	if m != nil && m.TimeStamp != nil {
		return *m.TimeStamp
	}
	return 0
}

//读条进度
type C2S_ProgressMsg struct {
	Pro                  *int32   `protobuf:"varint,1,opt,name=pro" json:"pro,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2S_ProgressMsg) Reset()         { *m = C2S_ProgressMsg{} }
func (m *C2S_ProgressMsg) String() string { return proto.CompactTextString(m) }
func (*C2S_ProgressMsg) ProtoMessage()    {}
func (*C2S_ProgressMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{4}
}

func (m *C2S_ProgressMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2S_ProgressMsg.Unmarshal(m, b)
}
func (m *C2S_ProgressMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2S_ProgressMsg.Marshal(b, m, deterministic)
}
func (m *C2S_ProgressMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2S_ProgressMsg.Merge(m, src)
}
func (m *C2S_ProgressMsg) XXX_Size() int {
	return xxx_messageInfo_C2S_ProgressMsg.Size(m)
}
func (m *C2S_ProgressMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_C2S_ProgressMsg.DiscardUnknown(m)
}

var xxx_messageInfo_C2S_ProgressMsg proto.InternalMessageInfo

func (m *C2S_ProgressMsg) GetPro() int32 {
	if m != nil && m.Pro != nil {
		return *m.Pro
	}
	return 0
}

//读条进度
type S2C_ProgressMsg struct {
	Id                   *uint64  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Pro                  *int32   `protobuf:"varint,2,opt,name=pro" json:"pro,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *S2C_ProgressMsg) Reset()         { *m = S2C_ProgressMsg{} }
func (m *S2C_ProgressMsg) String() string { return proto.CompactTextString(m) }
func (*S2C_ProgressMsg) ProtoMessage()    {}
func (*S2C_ProgressMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{5}
}

func (m *S2C_ProgressMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2C_ProgressMsg.Unmarshal(m, b)
}
func (m *S2C_ProgressMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2C_ProgressMsg.Marshal(b, m, deterministic)
}
func (m *S2C_ProgressMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2C_ProgressMsg.Merge(m, src)
}
func (m *S2C_ProgressMsg) XXX_Size() int {
	return xxx_messageInfo_S2C_ProgressMsg.Size(m)
}
func (m *S2C_ProgressMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_S2C_ProgressMsg.DiscardUnknown(m)
}

var xxx_messageInfo_S2C_ProgressMsg proto.InternalMessageInfo

func (m *S2C_ProgressMsg) GetId() uint64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *S2C_ProgressMsg) GetPro() int32 {
	if m != nil && m.Pro != nil {
		return *m.Pro
	}
	return 0
}

//操作输入消息
type C2S_InputMsg struct {
	Sid                  *int32   `protobuf:"varint,1,opt,name=sid" json:"sid,omitempty"`
	X                    *float32 `protobuf:"fixed32,2,opt,name=x" json:"x,omitempty"`
	Y                    *float32 `protobuf:"fixed32,3,opt,name=y" json:"y,omitempty"`
	Z                    *float32 `protobuf:"fixed32,4,opt,name=z" json:"z,omitempty"`
	FrameID              *uint32  `protobuf:"varint,5,opt,name=frameID" json:"frameID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2S_InputMsg) Reset()         { *m = C2S_InputMsg{} }
func (m *C2S_InputMsg) String() string { return proto.CompactTextString(m) }
func (*C2S_InputMsg) ProtoMessage()    {}
func (*C2S_InputMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{6}
}

func (m *C2S_InputMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2S_InputMsg.Unmarshal(m, b)
}
func (m *C2S_InputMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2S_InputMsg.Marshal(b, m, deterministic)
}
func (m *C2S_InputMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2S_InputMsg.Merge(m, src)
}
func (m *C2S_InputMsg) XXX_Size() int {
	return xxx_messageInfo_C2S_InputMsg.Size(m)
}
func (m *C2S_InputMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_C2S_InputMsg.DiscardUnknown(m)
}

var xxx_messageInfo_C2S_InputMsg proto.InternalMessageInfo

func (m *C2S_InputMsg) GetSid() int32 {
	if m != nil && m.Sid != nil {
		return *m.Sid
	}
	return 0
}

func (m *C2S_InputMsg) GetX() float32 {
	if m != nil && m.X != nil {
		return *m.X
	}
	return 0
}

func (m *C2S_InputMsg) GetY() float32 {
	if m != nil && m.Y != nil {
		return *m.Y
	}
	return 0
}

func (m *C2S_InputMsg) GetZ() float32 {
	if m != nil && m.Z != nil {
		return *m.Z
	}
	return 0
}

func (m *C2S_InputMsg) GetFrameID() uint32 {
	if m != nil && m.FrameID != nil {
		return *m.FrameID
	}
	return 0
}

//帧存储操作输入
type InputData struct {
	Id                   *uint64  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Sid                  *int32   `protobuf:"varint,2,opt,name=sid" json:"sid,omitempty"`
	X                    *float32 `protobuf:"fixed32,3,opt,name=x" json:"x,omitempty"`
	Y                    *float32 `protobuf:"fixed32,4,opt,name=y" json:"y,omitempty"`
	Z                    *float32 `protobuf:"fixed32,5,opt,name=z" json:"z,omitempty"`
	Roomseatid           *int32   `protobuf:"varint,6,opt,name=roomseatid" json:"roomseatid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InputData) Reset()         { *m = InputData{} }
func (m *InputData) String() string { return proto.CompactTextString(m) }
func (*InputData) ProtoMessage()    {}
func (*InputData) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{7}
}

func (m *InputData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InputData.Unmarshal(m, b)
}
func (m *InputData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InputData.Marshal(b, m, deterministic)
}
func (m *InputData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InputData.Merge(m, src)
}
func (m *InputData) XXX_Size() int {
	return xxx_messageInfo_InputData.Size(m)
}
func (m *InputData) XXX_DiscardUnknown() {
	xxx_messageInfo_InputData.DiscardUnknown(m)
}

var xxx_messageInfo_InputData proto.InternalMessageInfo

func (m *InputData) GetId() uint64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *InputData) GetSid() int32 {
	if m != nil && m.Sid != nil {
		return *m.Sid
	}
	return 0
}

func (m *InputData) GetX() float32 {
	if m != nil && m.X != nil {
		return *m.X
	}
	return 0
}

func (m *InputData) GetY() float32 {
	if m != nil && m.Y != nil {
		return *m.Y
	}
	return 0
}

func (m *InputData) GetZ() float32 {
	if m != nil && m.Z != nil {
		return *m.Z
	}
	return 0
}

func (m *InputData) GetRoomseatid() int32 {
	if m != nil && m.Roomseatid != nil {
		return *m.Roomseatid
	}
	return 0
}

//帧数据
type FrameData struct {
	FrameID              *uint32      `protobuf:"varint,1,opt,name=frameID" json:"frameID,omitempty"`
	Input                []*InputData `protobuf:"bytes,2,rep,name=input" json:"input,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *FrameData) Reset()         { *m = FrameData{} }
func (m *FrameData) String() string { return proto.CompactTextString(m) }
func (*FrameData) ProtoMessage()    {}
func (*FrameData) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{8}
}

func (m *FrameData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FrameData.Unmarshal(m, b)
}
func (m *FrameData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FrameData.Marshal(b, m, deterministic)
}
func (m *FrameData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FrameData.Merge(m, src)
}
func (m *FrameData) XXX_Size() int {
	return xxx_messageInfo_FrameData.Size(m)
}
func (m *FrameData) XXX_DiscardUnknown() {
	xxx_messageInfo_FrameData.DiscardUnknown(m)
}

var xxx_messageInfo_FrameData proto.InternalMessageInfo

func (m *FrameData) GetFrameID() uint32 {
	if m != nil && m.FrameID != nil {
		return *m.FrameID
	}
	return 0
}

func (m *FrameData) GetInput() []*InputData {
	if m != nil {
		return m.Input
	}
	return nil
}

//广播帧消息
type S2C_FrameMsg struct {
	Frames               []*FrameData `protobuf:"bytes,1,rep,name=frames" json:"frames,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *S2C_FrameMsg) Reset()         { *m = S2C_FrameMsg{} }
func (m *S2C_FrameMsg) String() string { return proto.CompactTextString(m) }
func (*S2C_FrameMsg) ProtoMessage()    {}
func (*S2C_FrameMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{9}
}

func (m *S2C_FrameMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2C_FrameMsg.Unmarshal(m, b)
}
func (m *S2C_FrameMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2C_FrameMsg.Marshal(b, m, deterministic)
}
func (m *S2C_FrameMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2C_FrameMsg.Merge(m, src)
}
func (m *S2C_FrameMsg) XXX_Size() int {
	return xxx_messageInfo_S2C_FrameMsg.Size(m)
}
func (m *S2C_FrameMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_S2C_FrameMsg.DiscardUnknown(m)
}

var xxx_messageInfo_S2C_FrameMsg proto.InternalMessageInfo

func (m *S2C_FrameMsg) GetFrames() []*FrameData {
	if m != nil {
		return m.Frames
	}
	return nil
}

//结果消息
type C2S_ResultMsg struct {
	WinnerID             *uint64  `protobuf:"varint,1,opt,name=winnerID" json:"winnerID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2S_ResultMsg) Reset()         { *m = C2S_ResultMsg{} }
func (m *C2S_ResultMsg) String() string { return proto.CompactTextString(m) }
func (*C2S_ResultMsg) ProtoMessage()    {}
func (*C2S_ResultMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{10}
}

func (m *C2S_ResultMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2S_ResultMsg.Unmarshal(m, b)
}
func (m *C2S_ResultMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2S_ResultMsg.Marshal(b, m, deterministic)
}
func (m *C2S_ResultMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2S_ResultMsg.Merge(m, src)
}
func (m *C2S_ResultMsg) XXX_Size() int {
	return xxx_messageInfo_C2S_ResultMsg.Size(m)
}
func (m *C2S_ResultMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_C2S_ResultMsg.DiscardUnknown(m)
}

var xxx_messageInfo_C2S_ResultMsg proto.InternalMessageInfo

func (m *C2S_ResultMsg) GetWinnerID() uint64 {
	if m != nil && m.WinnerID != nil {
		return *m.WinnerID
	}
	return 0
}

func init() {
	proto.RegisterEnum("pb.ID", ID_name, ID_value)
	proto.RegisterEnum("pb.ERRORCODE", ERRORCODE_name, ERRORCODE_value)
	proto.RegisterType((*C2S_ConnectMsg)(nil), "pb.C2S_ConnectMsg")
	proto.RegisterType((*S2C_ConnectMsg)(nil), "pb.S2C_ConnectMsg")
	proto.RegisterType((*S2C_JoinRoomMsg)(nil), "pb.S2C_JoinRoomMsg")
	proto.RegisterType((*S2C_StartMsg)(nil), "pb.S2C_StartMsg")
	proto.RegisterType((*C2S_ProgressMsg)(nil), "pb.C2S_ProgressMsg")
	proto.RegisterType((*S2C_ProgressMsg)(nil), "pb.S2C_ProgressMsg")
	proto.RegisterType((*C2S_InputMsg)(nil), "pb.C2S_InputMsg")
	proto.RegisterType((*InputData)(nil), "pb.InputData")
	proto.RegisterType((*FrameData)(nil), "pb.FrameData")
	proto.RegisterType((*S2C_FrameMsg)(nil), "pb.S2C_FrameMsg")
	proto.RegisterType((*C2S_ResultMsg)(nil), "pb.C2S_ResultMsg")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd) }

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 602 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x53, 0xdf, 0x6b, 0xdb, 0x30,
	0x10, 0xae, 0x6c, 0x27, 0x9d, 0xaf, 0x49, 0xaa, 0x89, 0x32, 0xcc, 0x18, 0x25, 0xb8, 0x0c, 0x42,
	0x3b, 0xfa, 0x90, 0xb1, 0xb7, 0xed, 0x65, 0x49, 0xda, 0xa5, 0xd0, 0x1f, 0xc8, 0x7b, 0x1b, 0xac,
	0x28, 0xb3, 0x96, 0x85, 0xc6, 0x96, 0x91, 0x55, 0xda, 0x14, 0xf6, 0xdf, 0xed, 0xff, 0xda, 0x38,
	0xd9, 0x72, 0x92, 0xb2, 0x37, 0x7f, 0x77, 0xbe, 0xef, 0xfb, 0x4e, 0x77, 0x07, 0xdd, 0x4c, 0x96,
	0xa5, 0x98, 0xcb, 0xd3, 0x42, 0x2b, 0xa3, 0x98, 0x57, 0xcc, 0xe2, 0xef, 0xd0, 0x1b, 0x0d, 0x93,
	0xdb, 0x91, 0xca, 0x73, 0xf9, 0xc3, 0x5c, 0x96, 0x73, 0xf6, 0x1a, 0x5e, 0x14, 0x4b, 0xb1, 0x92,
	0x7a, 0x3a, 0x8e, 0x48, 0x9f, 0x0c, 0x02, 0xde, 0x60, 0xcc, 0xcd, 0x84, 0x31, 0x4b, 0x39, 0x1d,
	0x47, 0x5e, 0x95, 0x73, 0x98, 0x1d, 0x40, 0xcb, 0xa8, 0x3b, 0x99, 0x47, 0xd0, 0x27, 0x83, 0x90,
	0x57, 0x20, 0xfe, 0x04, 0xbd, 0x64, 0x38, 0xda, 0xe4, 0x3f, 0x81, 0x50, 0x6a, 0xad, 0xf4, 0x48,
	0xa5, 0xd2, 0x0a, 0xf4, 0x86, 0xdd, 0xd3, 0x62, 0x76, 0x3a, 0xe1, 0xfc, 0x9a, 0x8f, 0xae, 0xc7,
	0x13, 0xbe, 0xce, 0xc7, 0xbf, 0x61, 0x1f, 0xcb, 0x2f, 0xd4, 0x22, 0xe7, 0x4a, 0x65, 0x58, 0x7f,
	0x08, 0xa0, 0x95, 0xca, 0x4a, 0x29, 0xcc, 0x22, 0xb5, 0x04, 0x2d, 0xbe, 0x11, 0x61, 0xaf, 0xa0,
	0xad, 0xcc, 0x2f, 0xa9, 0xcb, 0xc8, 0xeb, 0xfb, 0x83, 0x80, 0xd7, 0x88, 0x31, 0x08, 0x0a, 0xad,
	0xca, 0xc8, 0xef, 0xfb, 0x83, 0x16, 0xb7, 0xdf, 0x96, 0x4b, 0xe4, 0xa9, 0xca, 0x12, 0x29, 0xd3,
	0x28, 0xa8, 0xb9, 0x9a, 0x48, 0xfc, 0x0e, 0x3a, 0x28, 0x9f, 0x18, 0xa1, 0xad, 0xf7, 0x37, 0x10,
	0x9a, 0x45, 0x26, 0x13, 0x23, 0xb2, 0xc2, 0x4a, 0xfb, 0x7c, 0x1d, 0x88, 0x8f, 0x60, 0x1f, 0xdf,
	0xf2, 0x46, 0xab, 0xb9, 0x96, 0x65, 0x89, 0x05, 0x14, 0xfc, 0x42, 0xab, 0xda, 0x25, 0x7e, 0xc6,
	0xef, 0xab, 0x8e, 0x36, 0x7f, 0xea, 0x81, 0x57, 0x77, 0x12, 0x70, 0x6f, 0x91, 0xba, 0x22, 0x6f,
	0x5d, 0x94, 0x42, 0x07, 0x99, 0xa7, 0x79, 0x71, 0x6f, 0x6a, 0xda, 0xb2, 0x69, 0x1e, 0x3f, 0x59,
	0x07, 0xc8, 0xa3, 0xad, 0xf0, 0x38, 0x79, 0x44, 0xb4, 0x8a, 0xfc, 0x0a, 0xad, 0x10, 0x3d, 0xd9,
	0xe6, 0x3c, 0x4e, 0x9e, 0x58, 0x04, 0xbb, 0x3f, 0xb5, 0xc8, 0x70, 0x84, 0xad, 0x3e, 0x19, 0x74,
	0xb9, 0x83, 0xf1, 0x03, 0x84, 0x56, 0x61, 0x2c, 0x8c, 0xf8, 0x9f, 0x29, 0x94, 0xf4, 0x9e, 0x49,
	0xfa, 0x5b, 0x92, 0xc1, 0x96, 0x64, 0xcb, 0x49, 0x6e, 0x8f, 0xac, 0xfd, 0x7c, 0x64, 0xf1, 0x05,
	0x84, 0x67, 0xe8, 0xc1, 0x0a, 0x6f, 0xf8, 0x23, 0x5b, 0xfe, 0xd8, 0x11, 0xb4, 0x16, 0xe8, 0xcf,
	0x0e, 0x76, 0xaf, 0xda, 0x9a, 0xc6, 0x30, 0xaf, 0x72, 0xf1, 0x87, 0x6a, 0x64, 0x96, 0x0f, 0x9f,
	0xea, 0x2d, 0xb4, 0x6d, 0x7d, 0x19, 0x91, 0x75, 0x55, 0xa3, 0xc6, 0xeb, 0x64, 0x7c, 0x02, 0x5d,
	0x7c, 0x61, 0x2e, 0xcb, 0xfb, 0xa5, 0x3b, 0x83, 0x87, 0x45, 0x9e, 0x6f, 0x9e, 0x81, 0xc3, 0xc7,
	0x7f, 0x08, 0x78, 0xd3, 0x31, 0xeb, 0x42, 0x78, 0x99, 0x9c, 0xdf, 0x7e, 0x9e, 0x9c, 0x4f, 0xaf,
	0xe8, 0x0e, 0xdb, 0x87, 0x3d, 0x84, 0xf5, 0xaa, 0x53, 0xc2, 0x5e, 0x42, 0x17, 0x03, 0x5f, 0xa4,
	0xd0, 0x66, 0x26, 0x85, 0xa1, 0x1e, 0xa3, 0xd0, 0xc1, 0x90, 0xdb, 0x67, 0x0a, 0x2e, 0xe2, 0xf6,
	0x81, 0x1e, 0x38, 0x5a, 0x2e, 0x45, 0xba, 0xa2, 0x87, 0x0e, 0xda, 0x1d, 0xa4, 0x03, 0x07, 0x6d,
	0x07, 0x74, 0xe8, 0xa0, 0x7d, 0x06, 0xfa, 0x91, 0xf5, 0x00, 0xaa, 0x5a, 0x6c, 0x83, 0x9e, 0xb9,
	0xf4, 0x68, 0xa9, 0x4a, 0x49, 0x71, 0x64, 0xbb, 0x08, 0x27, 0x57, 0x63, 0xfa, 0x97, 0x1c, 0x7f,
	0x83, 0xb0, 0x39, 0x3a, 0x06, 0xd0, 0x9e, 0x70, 0x7e, 0x7b, 0x7d, 0x47, 0x77, 0xd0, 0x13, 0x7e,
	0x5f, 0xa9, 0x1b, 0x7b, 0xf8, 0x94, 0x20, 0x6f, 0x15, 0xb1, 0xae, 0x3d, 0x6c, 0x0d, 0x31, 0xa2,
	0xc4, 0x08, 0x23, 0xa9, 0x8f, 0x52, 0x18, 0xfa, 0x8a, 0x67, 0x4f, 0x83, 0x7f, 0x01, 0x00, 0x00,
	0xff, 0xff, 0x75, 0x2d, 0x30, 0xf6, 0x6c, 0x04, 0x00, 0x00,
}
